In [117]:
import numpy as np
import copy

In [118]:
def change_row(matrix, row1, row2):
    tmp = copy.copy(matrix[row1])
    matrix[row1] = matrix[row2]
    matrix[row2] = tmp

In [119]:
def get_row_multiplied(row, coefficient):
    result = []    
    for element in row:
        result.append(element * coefficient)
    return result

In [120]:

argumented = np.array([
    [1,  2, -1, 4],
    [2, -4, 0, 5.0],
])

n = argumented.shape[0]
m = argumented.shape[1]
# float_formatter = "{:.2f}".format
# np.set_printoptions(formatter={'float_kind':float_formatter})
# np.set_printoptions(precision=3)

In [121]:
lpr = 0
pivots = []
for column in range(m):
    
    pivot_founded = False
    
    # change row if pivot is 0
    if abs(argumented[lpr, column]) <= 0.00001:
        for row in range(lpr + 1, n):
            if argumented[row, column] != 0:
                change_row(argumented, lpr, row)
                print("-----------row change-----------")
                print(argumented)
                pivot_founded = True
                break
        if not pivot_founded:
            #this column doesn't have pivot
            continue
            
    pivots.append((lpr, column))
    # make pivot one
    pivot = argumented[lpr, column]
    argumented[lpr] = get_row_multiplied(argumented[lpr], 1 / pivot)
    print("---------divide to pivot--------")
    print(argumented)
    
    # make row under pivot zero
    for row in range(lpr + 1, n):
        argumented[row] += get_row_multiplied(argumented[lpr],-argumented[row, column])
        print("----make row under pivot zero----")
        print(argumented)
        
    
    if lpr == n-1:
        break
        
    lpr += 1
    


---------divide to pivot--------
[[1.00 2.00 -1.00 4.00]
 [2.00 -4.00 0.00 5.00]]
----make row under pivot zero----
[[1.00 2.00 -1.00 4.00]
 [0.00 -8.00 2.00 -3.00]]
---------divide to pivot--------
[[1.00 2.00 -1.00 4.00]
 [-0.00 1.00 -0.25 0.38]]


In [122]:
print(pivots)

[(0, 0), (1, 1)]


In [123]:
pivots = pivots[::-1]
for row, column in pivots:
    for upper_row in range(row - 1, -1, -1):
        argumented[upper_row] += get_row_multiplied(argumented[row],-argumented[upper_row, column])
        

In [124]:
print(argumented)

[[1.00 0.00 -0.50 3.25]
 [-0.00 1.00 -0.25 0.38]]


In [125]:
x = [10] * (m - 1)

In [126]:
def find_pivot_position_in_row(pivots, r):
    for row, column in pivots:
        if(row == r):
            return (row, column)

In [129]:
for row, column in pivots:
    x[column] = 0
    for col in range(m - 1):
        if column == pivot_position[1]:
            continue
        x[column] += -x[col] * argumented[row, col]
    x[column] += argumented[row, m - 1]

In [128]:
for indx, variable in enumerate(x):
    print(f'X{indx + 1} = {variable}')

X1 = 8.25
X2 = 2.875
X3 = 10
